### PR TITLE
Link directly to Todoist task from Kanbanist task card

### LINKED ISSUE #3: Link directly to Todoist task from Kanbanist task card.
By linking directly to Todoist tasks, there is less need for Kanbanist to be able to modify all the task element.

Todoist allows for directly linking to a task via e.g. https://todoist.com/showTask?id=2871852183.

### PR DESCRIPTION
**Pull request by darekkay**
Closes #3

### CODE REVIEW

**Comment by darekkay** [comment]
image

**Comment by mwakerman** [comment]
Hi @darekkay - thanks for the contribution! I've made the icon only show on hover and I've also made it slight smaller. Let me know what you think and I'll merge.

**Comment by darekkay** [comment]
Hey, it looks good 👍 However, it violates accessibility principles, as one cannot follow the links using a screen reader or just a keyboard. I've used screen reader utilities from [Bootstrap 4](https://getbootstrap.com/docs/4.0/utilities/screenreaders/) to make it accessible:

- The element is hidden in a way that it appears hidden but a screen reader is still able to pick it up
- Nothing changes for mouse users - the icon is hidden by default and visible on hover
- The icon link is focusable when tabbing through the elements

I've also rebased the changes onto master.

**Comment by mwakerman** [comment]
Awesome, looks good to me.

**Pull request merged**
